#!/bin/bash
# Provision ubuntu machines
# Setup rlcone
# Setup https://github.com/OpenTechStrategies/permanent-rclone-qa for tests

sudo apt-get update
sudo apt -y remove needrestart # Preventing script from getting stuck with message "Pending kernel upgrade"
sudo apt -y upgrade
sudo apt -y install software-properties-common
sudo apt -y install python3-pip
sudo apt -y install git
sudo apt -y install rclone
rclone config file # Show loaded or prospective rclone config file
rclone config touch # Create rclone config dir if does not exist
cd ~
git clone https://github.com/OpenTechStrategies/permanent-rclone-qa
cd permanent-rclone-qa
pip install -r requirements.txt
./create-files.py
CURRENTDATETIME=`date +"%Y-%m-%d_%T"`
echo "00 13 * * 1-5 ~/permanent-rclone-qa/upload-test.py test-tree/special-files/1000-1B --remote-dir=1000-10B-${CURRENTDATETIME}-parallel --log-file=log-1000-1B-${CURRENTDATETIME}.txt --remote=prod --archive-path='/archives/QA (0a21-0000)/My Files/'" >> uploadcron
crontab uploadcron
rm uploadcron
